# Generated by Django 5.1 on 2024-12-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_commentlikes_postlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
    ]
