# Generated by Django 5.1 on 2024-12-30 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_savedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedposts',
            name='save_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://kwebqbdcvbwonprlzwuy.supabase.co/storage/v1/object/public/profiles/default_profile_picture.jpg', max_length=1024, null=True),
        ),
    ]
